### ISSUE TITLE
PML does not function properly when lambda >> domain size

### ISSUE THREAD

**Issue by jackieyao0114** [ECP-WarpX/artemis#45] opened 2021-10-12 17:45 UTC
When the domain is much smaller than the excitation signal wavelength, the PML does not absorb waves properly, presented as:
1. waves form periodic patterns that does not agree with the signal frequency when PML are applied on the lateral boundaries.
2. waves are reflected by the PML when impinging the PML normally. Lateral boundaries are PEC + none (effectively PMC).

**Comment by ajnonaka** [comment] 2021-10-12 17:47
I recall doing some testing on normal boundaries and things looked ok - I'll try to replicate this result (or demonstrate the error).

**Comment by jackieyao0114** [comment] 2021-10-12 17:50
> I recall doing some testing on normal boundaries and things looked ok - I'll try to replicate this result (or demonstrate the error).

Your test was with periodic lateral boundaries. Periodic boundaries always work.

**Comment by ajnonaka** [comment] 2021-10-12 20:45
Are you more concerned about the signal that leaks away from the region between the electrode and ground to the lateral boundaries?  Or the signal as it approaches the output port?

**Comment by jackieyao0114** [comment] 2021-10-12 21:01
> Are you more concerned about the signal that leaks away from the region between the electrode and ground to the lateral boundaries? Or the signal as it approaches the output port?

Both... a realistic setup of our circuit is PML at all 5 domain boundaries and PEC at the bottom domain boundary. So our wave will most likely hit the PML normally (signals approaching the output) as well as tangentially (signals leaking away to the lateral boundaries)

**Comment by RevathiJambunathan** [comment] 2021-10-12 23:58
Can you add the input files here to reproduce the error

**Comment by ajnonaka** [comment] 2021-10-13 00:31
[inputs_simple.txt](https://github.com/ECP-WarpX/artemis/files/7333823/inputs_simple.txt)

This inputs file is a 1D wave with periodic x, pec z, and pec (lo-y) and pml (hi-y).  The wave reflects almost fully.  If you switch the z boundary conditions to periodic the wave exits gracefully.

This is a separate issue from the long wavelength issue, but related since it has to do with pml.

**Comment by jackieyao0114** [comment] 2021-10-13 02:55
Thank you! With the long wavelength, the errors are basically the same as you described.

> [inputs_simple.txt](https://github.com/ECP-WarpX/artemis/files/7333823/inputs_simple.txt)
> 
> This inputs file is a 1D wave with periodic x, pec z, and pec (lo-y) and pml (hi-y). The wave reflects almost fully. If you switch the z boundary conditions to periodic the wave exits gracefully.
> 
> This is a separate issue from the long wavelength issue, but related since it has to do with pml.

**Comment by ajnonaka** [comment] 2021-11-11 18:36
Addressed in WarpX PR https://github.com/ECP-WarpX/WarpX/pull/2541

**Closed as completed** 2021-12-07 00:40 UTC
